[package]
name = "surface-dial-daemon"
version = "0.1.0"
authors = ["Daniel Prilik <danielprilik@gmail.com>"]
edition = "2018"

[dependencies]
# custom fork which implements `Send` on UInputDevice
evdev-rs = { git = "https://github.com/daniel5151/evdev-rs.git", sha = "cc9060d" }
notify-rust = "4"
